[package]
name = "streamid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.7"
byteorder = "1.5.0"
bytes = "1.5.0"

[lib]
name = "streamid"
path = "src/lib.rs"
